version: "3.8"

services:
  crowdfunding_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crowdfunding_frontend
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true